version: '3.8'

services:
  backend:
    build:
      context: ./backend/KickAndrush
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      # SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/KickAndRush
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/KickAndRush
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/kickandrush
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  postgres:
    image: postgres:11
    environment:
      POSTGRES_DB: KickAndRush
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local