spring:
  web:
    resources:
      static-locations: META-INF:/resources, classpath:/resources, classpath:/static, classpath:/static/dist
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/KickAndRush
    username: postgres
    password: postgres
  devtools:
    restart:
      log-condition-evaluation-delta: false
  # jpa properties
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 200
      query:
        fail_on_pagination_over_collection_fetch: true
        jdbc:
        show_sql: true
        format_sql: true
        order-inserts: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        query:
          fail_on_pagination_over_collection_fetch:true
    hibernate.ddl-auto: update
    open-in-view: true
  #jpa:
   # hibernate:
   #   ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
#    show-sql: true
   #database: postgresql
    #database-platform: org.hibernate.dialect.PostgreSQLDialect
    #open-in-view: false
    #generate-ddl: true
    #show_sql: true
    #format_sql: ture
  servlet:
    multipart:
      location: C:\image\upload
      maxFileSize: 200MB
      maxRequestSize: 100MB
  batch:
    jdbc:
      initialize-schema: never
      # initialize-schema: always
    job:
      enabled: false # 자동 실행 방지
    #properties:
     # mail.smtp.auth: true
      #mail.smtp.ssl.enable: true
     # mail.smtp.ssl.trust: smtp.naver.com
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG           